`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 31 2023 00:18:50 CST (May 30 2023 16:18:50 UTC)

module SobelFilter_Not_1U_1U_4_0(in1, out1);
  input in1;
  output out1;
  wire in1;
  wire out1;
  INVX1 g2(.A (in1), .Y (out1));
endmodule


