// Generated by stratus_hls 21.20-p100  (96289.240513)
// Wed May 31 05:29:34 2023
// from ../SobelFilter.cpp
#ifndef CYNTH_PART_SobelFilter_SobelFilter_ROM_31X32_filter_coeffs_H_h
#define CYNTH_PART_SobelFilter_SobelFilter_ROM_31X32_filter_coeffs_H_h

#include "systemc.h"
#include "stratus_hls.h"
/* Include declarations of instantiated parts. */


/* Declaration of the synthesized module. */
struct SobelFilter_ROM_31X32_filter_coeffs_H : public sc_module {
  sc_in<sc_uint<1> > CE;
  sc_in<sc_uint<5> > in1;
  sc_out<sc_uint<32> > out1;
  sc_in<bool > clk;
  SobelFilter_ROM_31X32_filter_coeffs_H( sc_module_name name );
  SC_HAS_PROCESS(SobelFilter_ROM_31X32_filter_coeffs_H);
  /*const*/ sc_uint<32> filter_coeffs_H[31];
  void SobelFilter_ROM_31X32_filter_coeffs_H_filter_coeffs_H_thread_1();
};

#endif
